[project]
name = "gai-sdk"
version = "1.0.220"
description = "Refer to https://kakkoii1337.github.io/gai for more information"
readme = "README.md"
classifiers = [ "Programming Language :: Python :: 3.10", "Development Status :: 3 - Alpha", "License :: OSI Approved :: MIT License", "Intended Audience :: Science/Research", "Intended Audience :: Developers", "Operating System :: OS Independent", "Topic :: Software Development", "Topic :: Software Development :: Libraries :: Python Modules", "Topic :: Scientific/Engineering :: Artificial Intelligence",]
authors = [
    { name = "kakkoii1337", email = "kakkoii1337@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "gai-lib",
    "gai-chat",
    "gai-openai",
    "gai-messages",
    "gai-dialogues",
    "gai-asm",
    "gai-mcp",
]

[project.optional-dependencies]
    dev = [
        "gai-lib[dev]"
    ]

[tool.uv.sources]
    "gai-lib" = { path="lib", editable = true }
    "gai-chat" = { path="chat", editable = true }
    "gai-openai" = { path="openai", editable = true }
    "gai-messages" = { path="messages", editable = true }
    "gai-dialogues" = { path="dialogues", editable = true }
    "gai-asm" = { path="asm", editable = true }
    "gai-mcp" = { path="mcp", editable = true }

[build-system]
    requires = [ "hatchling",]
    build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
    packages = [
        "lib/src/gai",
        "chat/src/gai",
        "openai/src/gai",
        "messages/src/gai",
        "dialogues/src/gai",
        "asm/src/gai",
        "mcp/src/gai",
    ]