from pydantic import BaseModel
from gai.lib.logging import getLogger
logger = getLogger(__name__)

from typing import Literal, Any

class OrchStepPydantic(BaseModel):
    step_type: str = Literal["chat.send", "chat.reply"]
    sender: str
    recipient: str
    turn_no: int
    step_no: int
    is_pm: bool

class OrchPlanPydantic(BaseModel):
    dialogue_id: str
    round_no: int
    curr_turn_no: int = 0
    curr_step_no: int = 0
    steps: list[OrchStepPydantic] = []
    participants: list[str]
    flow_type: str = Literal["poll", "chain"]

# A "turn" represents a complete request-response interaction between the user and the assistant.
# - The "turn request" is initiated by the user, where the user acts as the sender and the assistant as the designated recipient.
# - The subsequent "turn response" is generated by the assistant, which then becomes the sender while the original user becomes the recipient.
# - In cases where the active participant is not the intended agent (i.e., it is not the agent's turn), the specific flow design determines whether third-party listeners or non-recipients are allowed to observe the exchange.

# A flow_diagram describes the turns that takes place in one round of dialogue
# A dialogue contains multiple rounds of chat
# A round contains multiple turns of chat

# Flow Types:
#
# "Poll" Flow - same query received in parallel but respond independently
#
# Example - Polling:
# User->>Agent1
# User->>Agent2
# User->>Agent3
#
# Round:
#        ├── Turn 1: User -> *: "Everybody, please introduce yourself."
#        ├── Turn 2: Node1 -> User: "Hi, my name is Sara. Nice to meet you!"
#        └── Turn 2: Node2 -> User: "Hello, I'm Diana. Pleasure to meet you!"

# "Chain" Flow - Each turn is a request-response pair - only recipient can respond and the rest can only listen
#
# Example - Chaining:
# User->>Agent1
# Agent1->>Agent2
# Agent2->>Agent3
#
# Round:
#        ├── Turn 1a: User -> Node1: "Sara, tell me a one paragraph story"
#        ├── Turn 1b: Node1 -> User: "Sure! Once upon a time..."
#        ├── Turn 2a: User -> Node2: "Please continue."
#        └── Turn 2b: Node2 -> User: "And they lived happily ever after."


        
class InterimTurn:
    def __init__(self, sender, recipient):
        self.sender = sender
        self.recipient = recipient


def parse_flow(dialogue_id: str, round_no: int, flow: str) -> OrchPlanPydantic:

    turns = flow.replace("->>", "-->").split("\n")
    turns = [turn.strip() for turn in turns if turn.strip()]

    # 1st pass: Convert flow into interim turns

    interim_turns = []
    for i, turn in enumerate(turns):
        if "-->" in turn:
            sender, recipient = turn.split("-->")
            sender = sender.strip()
            recipient = recipient.strip()
            interim_turns.append(InterimTurn(sender, recipient))

    # 2nd pass: Validate and classify the flow as poll or chain

    is_poll = True
    for i, turn in enumerate(interim_turns):

        # Always start with User
        # If subsequent turns are from User, then it is a poll

        if i == 0 and turn.sender != "User":
            raise ValueError("First turn must be from User")
        if turn.sender != "User":
            is_poll = False
    flow_type = "poll"
    if not is_poll:

        # We know it is not a poll, so we need to check if it is a chain

        is_chain = True
        for i, turn in enumerate(interim_turns):
            if i > 0 and interim_turns[i-1].recipient != turn.sender:
                is_chain = False

        if not is_chain:
            raise ValueError(
                "Invalid flow. Previous recipient must be the sender in a chain flow.")
        flow_type = "chain"

    # 3rd pass: Convert interim turns into OrchPlanPydantic

    plan = OrchPlanPydantic(
        dialogue_id=dialogue_id,
        round_no=round_no,
        participants=[],
        flow_type=flow_type
    )
    turn_no = 0
    step_no = 0
    participants = set()

    for i, turn in enumerate(interim_turns):
        turn.sender = "User"
        step = OrchStepPydantic(
            step_type="chat.send",
            sender=turn.sender,
            recipient=turn.recipient,
            turn_no=turn_no,
            step_no=step_no,
            is_pm = (flow_type == "poll")
        )
        plan.steps.append(step)
        step_no += 1

        step = OrchStepPydantic(
            step_type="chat.reply",
            sender=turn.recipient,
            recipient=turn.sender,
            turn_no=turn_no,
            step_no=step_no,
            is_pm = (flow_type == "poll")
        )
        plan.steps.append(step)
        step_no += 1

        participants.add(turn.sender)
        participants.add(turn.recipient)
        turn_no += 1

    plan.participants = list(participants)
    if "User" in plan.participants:
        plan.participants.remove("User")
    return plan
