services:

    gai-ttt:
        build:
            context: ..
            dockerfile: ./src/gai/ttt/Dockerfile
            args:
                CATEGORY: "ttt"
        image: kakkoii1337/gai-ttt:latest
        container_name: gai-ttt
        environment:
            DOCKER_BUILDKIT: 1
            LOG_LEVEL: "DEBUG"
            TZ: "Asia/Singapore"
            SWAGGER_URL: "/doc"
            DEFAULT_GENERATOR: "ttt-exllamav2-mistral7b"
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
                          driver: nvidia
                          count: all
        ports:
            - "12031:12031"
            - "5678:5678"
        networks:
            - gai-sandbox
        volumes:
            - ~/.gai:/app/.gai

        # Enabling wait-for-client for debugger to wait until preLaunchTask is done. But the debugger client FAILED TO START after preLaunchTask is done so
        # the container did not get pass this command, ie. stuck at Attaching to gai-ttt.
        # command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client main.py

        # Disabling wait-for-client for debugger to start immediately. The services can start as normal, but the debugger client failed to stop at breakpoints.
        command: python -m debugpy --listen 0.0.0.0:5678 main.py

        # Currently what works is to run the start container task independently and then run the attached debugger launch manually.


    nats01:
        image: nats:latest
        container_name: nats01
        ports:
        - "4222:4222"  # Client port
        - "8222:8222"  # Monitoring port
        - "6222:6222"  # Cluster port
        command:
          - "--cluster"
          - "nats://0.0.0.0:6222"
          - "--routes"
          - "nats://nats02:6223"
          - "--routes"
          - "nats://nats03:6224"
        restart: unless-stopped
        networks:
            - gai-sandbox

    # nats02:
    #     image: nats:latest
    #     container_name: nats02
    #     ports:
    #     - "4223:4222"  # Client port
    #     - "8223:8222"  # Monitoring port
    #     - "6223:6222"  # Cluster port
    #     command:
    #       - "--cluster"
    #       - "nats://0.0.0.0:6223"
    #       - "--routes"
    #       - "nats://nats01:6222"
    #       - "--routes"
    #       - "nats://nats03:6224"
    #     restart: unless-stopped
    #     networks:
    #         - gai-sandbox

    # nats03:
    #     image: nats:latest
    #     container_name: nats03
    #     ports:
    #     - "4224:4222"  # Client port
    #     - "8224:8222"  # Monitoring port
    #     - "6224:6222"  # Cluster port
    #     command:
    #       - "--cluster"
    #       - "nats://0.0.0.0:6224"
    #       - "--routes"
    #       - "nats://nats01:6222"
    #       - "--routes"
    #       - "nats://nats02:6223"
    #     restart: unless-stopped
    #     networks:
    #         - gai-sandbox

    gai-net01:
        build:
            context: ..
            dockerfile: ./src/gai/net/server/Dockerfile
        image: gai-net:latest
        container_name: gai-net01
        environment:
            NATS_URL: "nats://nats01:4222"
        networks:
            - gai-sandbox

networks:
  gai-sandbox:
    external: true
