services:

    # NATS Server <-> GAI Net Subscriber
    nats:
        image: nats:latest
        container_name: nats
        ports:
        - "4222:4222"  # Client port
        - "8222:8222"  # Monitoring port
        - "6222:6222"  # Cluster port
        environment:
        - NATS_SERVER_NAME=gai-nats-ttt
        command:
          - "--cluster"
          - "nats://0.0.0.0:6222"
          - "--routes"
          - "nats://192.168.1.100:6222"
          - "--routes"
          - "nats://192.168.1.200:6222"
        restart: unless-stopped
        networks:
            - gai-networks

    # NAT Server <-> GAI Net Subscriber -> GAI TTT API Server
    gai-net01:
        build:
            context: ..
            dockerfile: ./src/gai/net/server/Dockerfile
        image: kakkoii1337/gai-net-server:latest
        container_name: gai-net01
        environment:
            NATS_URL: "nats://nats:4222"
        networks:
            - gai-networks

networks:
    gai-networks:
        external: true