services:

    gai-net01:
        build:
            context: ..
            dockerfile: ./src/gai/net/server/Dockerfile
        image: gai-net:latest
        container_name: gai-net01
        environment:
        - NATS_URL="nats://nats01:4222"
        networks:
            - gai-sandbox

networks:
    gai-sandbox:
        external: true